---
title: "Lab: Distributional Regression"
author: ""
format:
  html: default
  pdf: default
execute:
    warning: false
---

Download the [freMTPL2sev](http://laub.au/ai/data/freMTPL2sev.parquet) and [freMTPL2freq](http://laub.au/ai/data/freMTPL2freq.parquet) datasets.

We want to look at severity, but the covariates are stored in the frequency dataset, thus we need to merge the two datasets and drop the `ClaimNb` column from the frequency dataset.

```{python}
import pandas as pd

sev_no_covars = pd.read_parquet('freMTPL2sev.parquet')
freq_df = pd.read_parquet('freMTPL2freq.parquet')

# Just pull out the covariates from the frequency dataset
covariates = freq_df.drop(columns=['ClaimNb'])

# Merge the severity data with the policyholder covariates
severity = pd.merge(sev_no_covars, covariates, on='IDpol', how='left')
severity = severity.dropna()
severity
```

Now we will try to predict claim severity, i.e. `ClaimAmount`, given the rest.

## Data dictionary

- `IDpol`: policy number (unique identifier)
- `Area`: area code (categorical, ordinal)
- `BonusMalus`: bonus-malus level between 50 and 230 (with reference level 100)
- `Density`: density of inhabitants per km^2^ in the city of the living place of the driver
- `DrivAge`: age of the (most common) driver in years
- `Exposure`: total exposure in yearly units
- `Region`: regions in France (prior to 2016)
- `VehAge`: age of the car in years
- `VehBrand`: car brand (categorical, nominal)
- `VehGas`: diesel or regular fuel car (binary)
- `VehPower`: power of the car (categorical, ordinal)
- `ClaimAmount`: size of the particular claim (**target**)

::: footer
Source: Nell et al. (2020), [Case Study: French Motor Third-Party Liability Claims](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3164764), SSRN.
:::


# GLM

1. Fit a gamma GLM using `statsmodels` with a log link function.
2. Report the average negative log-likelihood loss on the test set.
3. Compute the dispersion parameter using the code from the slides, and compare to `statsmodels`' implementation.

# CANN


1. Fit a CANN model.
2. Report the average negative log-likelihood loss on the test set.
3. Recompute the dispersion parameter using the adjusted model. 
   Hint: use the code from the slides and change the following line of code

   ```python
   mus = np.exp(np.sum(CANN.predict(X_train), axis = 1))
   ```

## MDN

1. Fit an MDN with 5 Gamma mixture components to predict the claim severity.
2. Change the distributional assumption from Gamma to [InverseGamma](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/InverseGamma).
   Hint: adjust the following code:

   ```python
   mixture_distribution = tfd.MixtureSameFamily(
       mixture_distribution=tfd.Categorical(probs=pis),
       components_distribution=tfd.Gamma(alphas, betas))
   ```
3.  Report the average negative log-likelihood loss on the test set for both models.

## Other Metrics

1. Compare the previous models using point-wise metrics such as MAE, MSE, and declare the best model based on these metrics. Which model is the best?
2. Compare the models using distributional metrics such as CRPS, log-likelihood. Which model is the best? Did the order change compared to the point-wise metrics?

## Monte Carlo Dropout

1. Construct any style of neural network to predict the claim severity. Then add dropout to some part of the network.
2. Apply Monte Carlo dropout 2000 times and store the test set predictions. Make a histogram of the average test negative log-likelihoods.