---
title: "Lab: LaTeX"
author: ""
format:
  html: default
  pdf: default
---

That lab looks at how to incorporate LaTeX into your Google Colab notebooks.
The purpose of this part of the lab is to enhance how you annotate your code.
With LaTeX, you can include equations into your notebooks.

<!-- ### What is LaTeX? -->

LaTeX is a typesetting system commonly used in research and other technical fields. It enables users to create high-quality documents with professional-looking mathematical and scientific equations, figures, and tables. 

You can create and edit your own LaTeX documents by using a desktop-based distribution such as [MikTeX](https://miktex.org/), or online using [Overleaf](https://overleaf.com/). However, in this lab we will just be looking at how you can incorporate LaTeX into Google Colab.

# LaTeX equations

There are two ways you can incorporate LaTeX equations: either by using the `$$` notation or by using the `\[\]` notation.

By wrapping your equation in one dollar sign (`$`), you can write mathematical expressions in-line. For example, `$E = mc^2$` ⇒ $E = mc^2$.

By wrapping your equation in two dollar signs (`$$`), you can write mathematical expressions in "display mode", which puts expressions on a standalone line: `$$a^2 + b^2 = c^2$$` ⇒ $$a^2 + b^2 = c^2$$

You can also create mathematical expressions in display mode by wrapping your expression in `\[` and `]\` symbols. However, this does not seem to work in Google Colab for now, so we recommend using the dollar sign notation instead.

# Advanced LaTeX mathematical expressions

Much of the functionality that LaTeX offers is activated using "tags". For example, take the following equation for the area of a circle: 

$$ \text{Area of Circle} = \pi r^2 $$

This equation is represented by the following LaTeX code:

```
$$ \text{Area of Circle} = \pi r^2 $$
```
As you can see, there are two tags in this expression. The `\text{}` tag converts the text in the expression from italicised to non-italicised. The `\pi` tag inserts a pi symbol.

Other tags include `\frac{}{}` (which requires two arguments), `\sqrt{}`, and `\partial`:
```
$$ \frac{\partial}{\partial x} = \sqrt{x}$$
```
$$ \frac{\partial}{\partial x} = \sqrt{x}$$

To insert a subscript, use an underscore:
```
$$y_{ij} = \alpha_i + \beta_j$$
```
$$y_{ij} = \alpha_i + \beta_j$$
