#!/usr/bin/env python3
"""
Fix up the autogenerated "Other Formats" box on lecture web pages.

Two changes, both scoped to that box so no other page text is touched:
  * rename Quarto's "RevealJS" entry to "Slides (html)";
  * add a "Slides (pdf)" entry pointing at the slide PDF.

Quarto lists the RevealJS slides under "Other Formats" but knows nothing about
the slide PDFs that decktape_pdfs.py produces afterwards. Each lecture's web page
(<name>.html) has a sibling <name>.pdf, so we derive the PDF link from the HTML
filename and splice an extra <li> into the existing alternate-formats list.

Scoped to docs/Lectures/ — only lectures use RevealJS plus a decktape slide PDF.
Labs/Exercises render a genuine LaTeX PDF through Quarto's own pdf format and are
left completely untouched.

Runs as a Quarto post-render script. Position in the post-render list doesn't
matter: it keys off the .slides.html Quarto writes during render, not decktape's
PDF. Operates on the files in QUARTO_PROJECT_OUTPUT_FILES; falls back to a glob of
docs/Lectures/*.html when run by hand. Idempotent — the box converges to the same
final state regardless of prior contents, so re-runs and re-renders leave it
unchanged.

Usage (manual):
    python scripts/add_pdf_format_link.py
"""

import os
import re
import sys
from glob import glob
from pathlib import Path

OUTPUT_DIR = "docs"

# The whole autogenerated box: <div class="quarto-alternate-formats">...</div>.
# There are no nested <div>s inside it, so a non-greedy match to the first
# </div> grabs exactly the box.
ALT_FORMATS_RE = re.compile(
    r'<div class="quarto-alternate-formats">.*?</div>',
    re.DOTALL,
)


def add_pdf_link(html_path: Path) -> bool:
    """Fix up the Other Formats box. Returns True if the page was modified."""
    # Key off the .slides.html (a Quarto render output, present before any
    # post-render script) rather than the decktape PDF, so we work no matter
    # where this script sits in the post-render order. Every lecture with
    # slides gets a same-stemmed PDF from decktape.
    slides_path = html_path.with_name(html_path.stem + ".slides.html")
    if not slides_path.exists():
        return False  # Not a RevealJS lecture — nothing to link.
    pdf_name = html_path.with_suffix(".pdf").name  # Same stem, same directory.

    content = html_path.read_text(encoding="utf-8")

    match = ALT_FORMATS_RE.search(content)
    if not match:
        return False  # Page has no Other Formats box.

    block = match.group(0)

    # Rename Quarto's RevealJS entry (scoped to this box).
    new_block = block.replace(">RevealJS</a>", ">Slides (html)</a>")

    # Drop any existing PDF entry — covers an older label from a prior run —
    # then re-add it fresh after the slides entry, so we always converge to
    # the same markup no matter the box's prior state.
    pdf_li = (
        f'<li><a href="{pdf_name}">'
        f'<i class="bi bi-file-pdf"></i>Slides (pdf)</a></li>'
    )
    new_block = re.sub(
        rf'<li><a href="{re.escape(pdf_name)}">.*?</a></li>', "", new_block
    )
    idx = new_block.rfind("</ul>")
    new_block = new_block[:idx] + pdf_li + new_block[idx:]

    if new_block == block:
        return False  # Already in the desired state.

    content = content[: match.start()] + new_block + content[match.end():]
    html_path.write_text(content, encoding="utf-8")
    return True


def target_files() -> list[Path]:
    """Lecture web pages to process: changed files from Quarto, else a glob.

    Restricted to docs/Lectures/ so Labs/Exercises (which use Quarto's real
    LaTeX pdf format) are never touched.
    """
    env = os.getenv("QUARTO_PROJECT_OUTPUT_FILES", "").strip()
    if env:
        candidates = env.split("\n")
    else:
        candidates = glob(f"{OUTPUT_DIR}/Lectures/*.html")

    return [
        Path(f)
        for f in candidates
        if f.endswith(".html")
        and not f.endswith(".slides.html")
        and "Lectures" in Path(f).parts
    ]


def main() -> None:
    files = target_files()
    modified = 0
    for path in files:
        if path.exists() and add_pdf_link(path):
            modified += 1
            print(f"✓ {path}")

    print(f"\nUpdated Other Formats on {modified} of {len(files)} pages")


if __name__ == "__main__":
    main()
