#!/usr/bin/env python3
"""
Self-host the project's Google Fonts as embedded (data-URI) @font-face rules.

The slide PDFs are produced by screenshotting reveal.js in headless Chrome
(see decktape_pdfs.py). When the heading/body font (Playfair Display) is loaded
from Google Fonts with `display=swap`, a slow/flaky network lets decktape
capture the title slide before the font arrives — so it renders in the Times
fallback at the wrong size. Fetching fonts over the network at render time is
the root cause.

This script downloads the needed faces once and writes them as base64 data-URI
@font-face rules into SCSS partials, so neither the PDFs nor the live site touch
the network for fonts. It is path-independent (data URIs), so it works for both
the deep-nested reveal and bootstrap theme CSS and under any deployment subpath.

Run it again to regenerate after changing the font stack:

    python3 scripts/embed_fonts.py

Then make sure the generated partials are listed in the relevant `theme:` lists
in _quarto.yml, and that the original `@import url(fonts.googleapis...)` lines
have been removed from shared.scss / html-style.scss.
"""

import base64
import re
import urllib.request
from pathlib import Path

# A recent browser UA so Google returns woff2 (and variable fonts).
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)

# Only Latin subsets are needed for an English deck.
SUBSETS = {"latin", "latin-ext"}

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# output partial -> Google Fonts css2 URL(s) to embed into it.
# Only the slide-critical fonts are embedded: Playfair Display (headings/body of
# the slides) and Fira Code (code). The HTML-only body font (Source Serif 4) is
# left on Google Fonts — it never appears in the slide PDFs, and inlining its
# large optical-size variable face would bloat the render-blocking HTML CSS.
TARGETS = {
    # Used by BOTH the slides and the HTML site (headings + code).
    "fonts.scss": [
        "https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700"
        "&family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap",
    ],
}

HEADER = (
    "/*-- scss:rules --*/\n"
    "/* GENERATED by scripts/embed_fonts.py — do not edit by hand.\n"
    "   Google Fonts embedded as data URIs so rendering never hits the network\n"
    "   (which is what corrupted the title slide in the slide PDFs). */\n"
)


def _fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read() if binary else resp.read().decode("utf-8")


def _faces(css):
    """Yield (subset, family, style, weight, unicode_range, woff2_url) per face."""
    parts = re.split(r"/\*\s*([a-z0-9-]+)\s*\*/", css)
    for i in range(1, len(parts), 2):
        subset, block = parts[i], parts[i + 1]
        if subset not in SUBSETS:
            continue
        yield (
            subset,
            re.search(r"font-family:\s*'([^']+)'", block).group(1),
            re.search(r"font-style:\s*(\w+)", block).group(1),
            re.search(r"font-weight:\s*([\d ]+);", block).group(1).strip(),
            re.search(r"unicode-range:\s*([^;]+);", block).group(1).strip(),
            re.search(r"src:\s*url\(([^)]+)\)", block).group(1),
        )


def _rule(family, style, weight, unicode_range, woff2):
    b64 = base64.b64encode(woff2).decode()
    return (
        "@font-face {\n"
        f"  font-family: '{family}';\n"
        f"  font-style: {style};\n"
        f"  font-weight: {weight};\n"
        "  font-display: swap;\n"
        f'  src: url("data:font/woff2;base64,{b64}") format("woff2");\n'
        f"  unicode-range: {unicode_range};\n"
        "}"
    )


def main():
    for out_name, urls in TARGETS.items():
        rules, raw_total = [], 0
        for url in urls:
            for subset, fam, style, weight, urange, woff2_url in _faces(_fetch(url)):
                woff2 = _fetch(woff2_url, binary=True)
                raw_total += len(woff2)
                rules.append(_rule(fam, style, weight, urange, woff2))
                print(f"  {out_name}: {fam} {style} {weight} [{subset}] {len(woff2)//1024} KB")
        out_path = PROJECT_ROOT / out_name
        out_path.write_text(HEADER + "\n" + "\n".join(rules) + "\n", encoding="utf-8")
        size = out_path.stat().st_size
        print(f"-> {out_name}: {len(rules)} faces, {raw_total//1024} KB raw, {size//1024} KB scss\n")


if __name__ == "__main__":
    main()
